# Generated by Django 6.0.6 on 2026-06-04 17:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionDeployment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('github_repo_url', models.CharField(max_length=255)),
                ('branch', models.CharField(default='main', max_length=50)),
                ('aws_instance_id', models.CharField(blank=True, max_length=100, null=True)),
                ('elastic_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OFFLINE', 'Offline'), ('VERIFYING', 'Verifying Contract'), ('PROVISIONING', 'Provisioning EC2'), ('RUNNING', 'Running'), ('FAILED', 'Failed')], default='OFFLINE', max_length=20)),
                ('config_snapshot', models.JSONField(blank=True, help_text='The parsed velzion.yaml matrix', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_deployments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
