# Generated by Django 6.0.6 on 2026-06-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velzard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productiondeployment',
            name='status',
            field=models.CharField(choices=[('OFFLINE', 'Offline'), ('VERIFYING', 'Verifying Contract'), ('PROVISIONING', 'Provisioning EC2'), ('COMPILING', 'Compiling Code'), ('RUNNING', 'Running'), ('DESTROYING', 'Terminating Cluster'), ('FAILED', 'Failed')], default='OFFLINE', max_length=20),
        ),
    ]
