# Generated by Django 6.0.6 on 2026-06-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velzard', '0002_alter_productiondeployment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='productiondeployment',
            name='container_status',
            field=models.JSONField(blank=True, default=list, help_text='Parsed active container list'),
        ),
        migrations.AddField(
            model_name='productiondeployment',
            name='instance_type',
            field=models.CharField(default='t3.small', max_length=50),
        ),
        migrations.AddField(
            model_name='productiondeployment',
            name='telemetry_history',
            field=models.JSONField(blank=True, default=list, help_text='Rolling 15-tick history of CPU/RAM'),
        ),
        migrations.AddField(
            model_name='productiondeployment',
            name='volume_size',
            field=models.IntegerField(default=30),
        ),
    ]
