# Generated by Django 6.0.6 on 2026-06-21 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velzard', '0003_productiondeployment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='productiondeployment',
            name='ascended_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when infrastructure went live', null=True),
        ),
    ]
