# Generated by Django 6.0.5 on 2026-05-27 18:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('github_repo_url', models.URLField(max_length=255)),
                ('aws_role_arn', models.CharField(max_length=255)),
                ('vpc_id', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EphemeralEnvironment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pr_number', models.IntegerField()),
                ('status', models.CharField(choices=[('PROVISIONING', 'Provisioning'), ('RUNNING', 'Running'), ('SLEEPING', 'Sleeping'), ('DESTROYED', 'Destroyed')], default='PROVISIONING', max_length=20)),
                ('dns_prefix', models.CharField(blank=True, max_length=50, null=True)),
                ('instance_id', models.CharField(blank=True, max_length=50, null=True)),
                ('ttl_expires_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environments', to='zegion.project')),
            ],
        ),
    ]
