# Generated by Django 6.0.5 on 2026-05-28 11:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zegion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ephemeralenvironment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
