# Generated by Django 6.0.5 on 2026-06-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zegion', '0002_ephemeralenvironment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ephemeralenvironment',
            name='terminated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ephemeralenvironment',
            name='terminated_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ephemeralenvironment',
            name='status',
            field=models.CharField(choices=[('PROVISIONING', 'Provisioning'), ('RUNNING', 'Running'), ('SLEEPING', 'Sleeping'), ('WAKING', 'Waking'), ('DESTROYED', 'Destroyed')], default='PROVISIONING', max_length=20),
        ),
    ]
