# Generated by Django 6.0.5 on 2026-06-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zegion', '0003_ephemeralenvironment_terminated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ephemeralenvironment',
            name='status',
            field=models.CharField(choices=[('PROVISIONING', 'Provisioning'), ('RUNNING', 'Running'), ('BUILT', 'Built'), ('SLEEPING', 'Sleeping'), ('WAKING', 'Waking'), ('DESTROYED', 'Destroyed')], default='PROVISIONING', max_length=20),
        ),
    ]
