# Generated by Django 6.0.6 on 2026-06-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_allowed_repos'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='aws_iam_role_arn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
